SOURCE_DIR=app

function help() {

  clear
  echo "================= Usage ================="
  echo "bandit                   : Install and run bandit security analysis."
  echo "clean                    : Remove autogenerated folders"
  echo "mypy                     : Install and run mypy type checking."
  echo "flake8                   : Install and run flake8 linting."
  echo "linter                   : Intall and run flake8, mypy and bandit"
  echo "install_requirements     : Install all the packages listed in *requirements*.txt files."
  echo "test                     : Run tests and generate coverage report."
  echo "venv                   : Create Python venv, use it by running 'source ./venv/bin/activate'"
}

function init() {
  venv
}

function clean() {
  rm -rf .mypy_cache/
}

function venv() {
  python3 -m venv ./venv
}

# Run bandit security analysis, assumes your environment has dependencies installed
function run_bandit() {
  echo "bandit running"
  bandit -r "$SOURCE_DIR"
}

# Run mypy type checking, assumes your environment has dependencies installed
function run_mypy() {
  echo "mypy Running"
  mypy --install-types --non-interactive $SOURCE_DIR
  mypy "$SOURCE_DIR"
}

# Run flake8 linting, assumes your environment has dependencies installed
function run_flake8() {
  echo "Running flake8..."
  flake8 "$SOURCE_DIR" main.py
}

function run_linter() {
  run_flake8
  run_mypy
  run_bandit
}

# Install all the packages listed in *requirements*.txt files.
function install_requirements() {
  find . -name '*requirements*.txt' -exec python -m pip install -r {} \;
}

# Run tests, assumes your environment has dependencies installed
function test() {
  pytest
}


case $1 in
"help") help ;;
"bandit") run_bandit ;;
"clean") clean ;;
"mypy") run_mypy ;;
"flake8") run_flake8 ;;
"linter") run_linter ;;
"install_requirements") install_requirements ;;
"test") test ;;
"venv") venv ;;
"init") init;;
*) help ;;
esac
